apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-sre-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "test-sre-chart.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "test-sre-chart.name" . }}

    spec:
      containers:
        - name: test-sre-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 80

          livenessProbe:
            httpGet:
              path: /users
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /users
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY

            - name: AWS_DEFAULT_REGION
              value: "us-east-2"

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
